import mongoose, {model, Schema, models} from "mongoose";

const CampsiteSchema = new Schema({
  user:{type:String, required:true},
  title: {type:String, required:true},
  description: String,
  price: Number,
  priceDefaultType: String,
  priceBungalow: Number,
  priceVan: Number,
  isPaymentCash: Boolean,
  isPaymentCreditCard: Boolean,
  isPaymentIban: Boolean,
  isPriceVisible: Boolean,
  images: [{type:String}],
  address: String,
  city: String,
  district: String,
  contactTel: String,
  contactInstagram: String,
  contactFacebook: String,
  isReservationModuleAvailable: Boolean,
  isReservationModuleBungalowRentingPossible: Boolean,
  isPublicTransportationPossible: Boolean,
  mapLatitute: String,
  mapLangtitute: String,

  isFriendlyVan: Boolean,
  descriptionVan: String,
  isFriendlyKid: Boolean,
  descriptionKid: String,
  isFriendlyRemoteWork: Boolean,
  descriptionRemoteWork: String,
  isFriendlyPet: Boolean,
  descriptionPet: String,
  isFriendlyAlcohol: Boolean,

  isPresentWC: Boolean,
  isPresentParkLot: Boolean,
  isPresentShower: Boolean,
  isPresentHotWater: Boolean,
  isPresentWifi: Boolean,
  isPresentKitchen: Boolean,
  isPresentFridge: Boolean,
  isPresentLaundry: Boolean,
  isPresentFirePit: Boolean,
  isPresentElectricity: Boolean,
  isPresentPrivateBeach: Boolean,
  isPresentBungalow: Boolean,
  isPresentDishwasher: Boolean,
  isPresentBreakfastIncluded: Boolean,
  isPresentSunbedIncluded: Boolean,
  isPresentSunbedRenting: Boolean,
  isPresentMicrowave: Boolean,
  isPresentStowe: Boolean,
  isPresentPicnicTable: Boolean,

  isNearSea: Boolean,
  distanceSea: Number,
  isNearLake: Boolean,
  distanceLake: Number,
  isNearForest: Boolean,
  distanceForest: Number,
  isNearRestaurant: Boolean,
  distanceRestaurant: Number,
  isNearStore: Boolean,
  distanceStore: Number,
  isNearBar: Boolean,
  distanceBar: Number,
  
  activitiesYoga: Boolean,
  activitiesCanoing: Boolean,
  activitiesTrekking: Boolean,
  activitiesSurf: Boolean,
  activitiesBeachVolleyball: Boolean,
  activitiesVolleyball: Boolean,
  activitiesSpa: Boolean,
  activitiesAtv: Boolean,
  activitiesParagliding: Boolean,
  activitiesBoatRental: Boolean,
  activitiesBoatTour: Boolean,
  activitiesPool: Boolean ,
  
  isEnglishSpoken: Boolean,
  isGermanSpoken: Boolean,
  isRussianSpoken: Boolean,
  isSpanishSpoken: Boolean,
  titleEnglish: String,
  descriptionEnglish: String,
  
}, {
  timestamps: true,
});

export const Campsite = models.Campsite || model('Campsite', CampsiteSchema);